### ISSUE TITLE
Pasar el string de md5 a bits

### ISSUE THREAD

**Issue by dylanforit** [AgoraUS-G2-1617/G27#16]
Una vez se tenga el String de md5 la pasaremos a bits.

**Comment by andgagon** [comment]
Creado metodo para el paso de md5 a bits testeado.
Pasamos a unir las ramas y posteriormente probamos que jenkins ejecuta el test correctamente

**Comment by alegargar** [comment]
Correctos test e integracion con jenkins.
Procedo a cerrar la incidencia.
