### ISSUE TITLE
Comentarios explicativos

### ISSUE THREAD

**Issue by andgagon** [AgoraUS-G2-1617/G27#4]
La mayoría de funciones implementadas por el grupo de verificación anterior carecen de comentarios explicativos.
Solución: Investigar, seguir la traza de los métodos y comentar de forma acorde

**Comment by andgagon** [comment]
AuthorityImpl comentado al completo
Gestor de BD comentado al completo

**Comment by Hug0Ramos** [comment]
Tests comentados
